// GENERATED by android/tools/gen_tokens.py from design/tokens.json (fetched 2026-06-14).
// Do not edit by hand: change design/tokens.json (or the DARK table in the generator) and regenerate.
package com.tmantoinelaw.portal.core.ui.theme

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.unit.dp

object Tokens {
    object Brand {
        val black = Color(0xFF000000)
        val white = Color(0xFFFFFFFF)
        val primary = Color(0xFF03A5E9)
        val primaryDark = Color(0xFF136DA0)
        val tint1 = Color(0xFFE6F6FD)
        val tint2 = Color(0xFFE7F0F6)
    }
    object Accent {
        val indigo = Color(0xFF136DA0)
        val purple = Color(0xFF136DA0)
        val violet = Color(0xFFB899EB)
        val blue = Color(0xFF7DBBFF)
        val mint = Color(0xFF6BE6D3)
        val cyan = Color(0xFFA0BCE8)
        val green = Color(0xFF71DD8C)
        val pink = Color(0xFFFF90E8)
        val orange = Color(0xFFFFB55B)
        val yellow = Color(0xFFFFCC00)
        val red = Color(0xFFFF4747)
    }
    object Chart {
        val cyan = Color(0xFFA0BCE8)
        val mint = Color(0xFF6BE6D3)
        val black = Color(0xFF000000)
        val blue = Color(0xFF7DBBFF)
        val purple = Color(0xFFB899EB)
        val green = Color(0xFF71DD8C)
        val orange = Color(0xFFFFB55B)
        val yellow = Color(0xFFFFCC00)
        val pink = Color(0xFFFF90E8)
        val red = Color(0xFFFF4747)
    }
    object Light {
        val page = Color(0xFFF5F5F7)
        val surface = Color(0xFFFFFFFF)
        val card = Color(0xFFF9F9FA)
        val panel = Color(0xFFF9F9FA)
        val input = Color(0xCCFFFFFF)
        val popup = Color(0xE6FFFFFF)
        val popupGlass = Color(0xCCFFFFFF)
        val tooltip = Color(0xCC000000)
        val tag = Color(0xFFE6F6FD)
        val code = Color(0xFF1E1E1E)
        val ink = Color(0xFF000000)
        val inkSecondary = Color(0x66000000)
        val inkMuted = Color(0x8C000000)
        val placeholder = Color(0x33000000)
        val link = Color(0xFF03A5E9)
        val hint = Color(0xFF136DA0)
        val borderSoft = Color(0x1A000000)
        val borderMedium = Color(0x33000000)
        val borderStrong = Color(0x66000000)
        val borderHeavy = Color(0xCC000000)
        val hover = Color(0x0A000000)
        val hoverDeep = Color(0x14000000)
        val active = Color(0x1F000000)
        val inactive = Color(0x66000000)
        val accentBg = Color(0x14136DA0)
        val accentBgHover = Color(0x1F136DA0)
        val dashCard1 = Color(0xFFE6F6FD)
        val dashCard2 = Color(0xFFE7F0F6)
        val kpi1 = Color(0xFF03A5E9)
        val kpi2 = Color(0xFF136DA0)
    }
    object Dark {
        val page = Color(0xFF161616)
        val surface = Color(0xFF1C1C1C)
        val card = Color(0xFF2A2A2C)
        val panel = Color(0xFF232325)
        val input = Color(0x12FFFFFF)
        val popup = Color(0xEB28282A)
        val popupGlass = Color(0xD928282A)
        val tooltip = Color(0xCC000000)
        val tag = Color(0xFF18323D)
        val code = Color(0xFF111214)
        val ink = Color(0xE6FFFFFF)
        val inkSecondary = Color(0x9EFFFFFF)
        val inkMuted = Color(0x8CFFFFFF)
        val placeholder = Color(0x40FFFFFF)
        val link = Color(0xFF03A5E9)
        val hint = Color(0xFF03A5E9)
        val borderSoft = Color(0x1FFFFFFF)
        val borderMedium = Color(0x47FFFFFF)
        val borderStrong = Color(0x73FFFFFF)
        val borderHeavy = Color(0xD9FFFFFF)
        val hover = Color(0x14FFFFFF)
        val hoverDeep = Color(0x1FFFFFFF)
        val active = Color(0x29FFFFFF)
        val inactive = Color(0x66FFFFFF)
        val accentBg = Color(0x2903A5E9)
        val accentBgHover = Color(0x3D03A5E9)
        val dashCard1 = Color(0xFF1E2B38)
        val dashCard2 = Color(0xFF29243A)
        val kpi1 = Color(0xFF0286BD)
        val kpi2 = Color(0xFF10557C)
    }
    object Type {
        data class Step(val size: Int, val lineHeight: Int, val weight: FontWeight)
        val text12 = Step(12, 16, FontWeight.Normal)
        val text14 = Step(14, 20, FontWeight.Normal)
        val text14sb = Step(14, 20, FontWeight.SemiBold)
        val text18 = Step(18, 28, FontWeight.Normal)
        val text18sb = Step(18, 28, FontWeight.SemiBold)
        val text24sb = Step(24, 32, FontWeight.SemiBold)
        val text48 = Step(48, 56, FontWeight.Normal)
        val text48sb = Step(48, 56, FontWeight.SemiBold)
        val text64sb = Step(64, 72, FontWeight.SemiBold)
        val heading64 = Step(64, 72, FontWeight.Normal)
        val heading128 = Step(128, 136, FontWeight.Bold)
        const val fontFeatures = "ss01, cv01"
    }
    object Space {
        val s2 = 2.dp
        val s4 = 4.dp
        val s6 = 6.dp
        val s8 = 8.dp
        val s12 = 12.dp
        val s14 = 14.dp
        val s16 = 16.dp
        val s20 = 20.dp
        val s24 = 24.dp
        val s28 = 28.dp
        val s32 = 32.dp
        val s40 = 40.dp
        val s48 = 48.dp
        val s56 = 56.dp
        val s64 = 64.dp
        val s80 = 80.dp
    }
    object Radius {
        val r4 = 4.dp
        val r6 = 6.dp
        val r8 = 8.dp
        val r12 = 12.dp
        val r14 = 14.dp
        val r16 = 16.dp
        val r20 = 20.dp
        val r24 = 24.dp
        val r28 = 28.dp
        val r32 = 32.dp
        val r48 = 48.dp
        val pill = 80.dp
    }
    object Size {
        val sm = 24.dp
        val md = 28.dp
        val lg = 32.dp
        val xl = 40.dp
        val xxl = 48.dp
        val xxxl = 56.dp
    }
    object Button {
        data class Size(val minHeight: Int, val paddingX: Int, val paddingY: Int, val radius: Int, val fontSize: Int, val lineHeight: Int)
        val small = Size(24, 12, 4, 12, 12, 16)
        val medium = Size(28, 12, 4, 14, 14, 20)
        val large = Size(32, 16, 6, 16, 14, 20)
        val xlarge = Size(40, 20, 8, 20, 16, 24)
        val textRadius = 80.dp
    }
    object Card { val radius = 16.dp; val gap = 8.dp }
    object Input { val radius = 16.dp }
    object Tag { val radius = 8.dp }
    object Tooltip { val radius = 12.dp; val paddingX = 8.dp; val paddingY = 4.dp; val maxWidth = 255.dp; val arrow = 8.dp }
    object Popup { val widthCompact = 480.dp; val widthLarge = 600.dp; val radiusCompact = 24.dp; val radiusLarge = 32.dp }
    object Layout { val contentMaxWidth = 1200.dp; val mobileWidth = 393.dp }
    object Motion { const val fastMs = 120; const val baseMs = 150 }
    object Opacity { const val inactive = 0.4f; const val white80 = 0.8f }
}
