{{-- TMA common components — include once in layout --}}
<link rel="preconnect" href="https://fonts.googleapis.com">
<link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;600&display=swap" rel="stylesheet">
<link rel="stylesheet" href="{{ asset('css/components.css') }}">
<link rel="stylesheet" href="{{ asset('css/table.css') }}">
<link rel="stylesheet" href="{{ asset('css/function-bar.css') }}">
<link rel="stylesheet" href="{{ asset('css/pagination.css') }}">
<link rel="stylesheet" href="{{ asset('css/filter-and-sort.css') }}">
<link rel="stylesheet" href="{{ asset('css/status-badge.css') }}">
<link rel="stylesheet" href="{{ asset('css/table-a.css') }}">
<link rel="stylesheet" href="{{ asset('css/table-b.css') }}">
<link rel="stylesheet" href="{{ asset('css/table-b-sessions.css') }}">
<link rel="stylesheet" href="{{ asset('css/table-c.css') }}">
<link rel="stylesheet" href="{{ asset('css/table-search.css') }}">
<link rel="stylesheet" href="{{ asset('css/table-add-data.css') }}">
<link rel="stylesheet" href="{{ asset('css/table-filter-sort.css') }}">
<link rel="stylesheet" href="{{ asset('css/global-search.css') }}">
<link rel="stylesheet" href="{{ asset('css/toast.css') }}">
<link rel="stylesheet" href="{{ asset('css/date-picker.css') }}">
<link rel="stylesheet" href="{{ asset('css/popover.css') }}">
<link rel="stylesheet" href="{{ asset('css/card.css') }}">
<link rel="stylesheet" href="{{ asset('css/input.css') }}">
<link rel="stylesheet" href="{{ asset('css/strip.css') }}">
<link rel="stylesheet" href="{{ asset('css/line.css') }}">
<link rel="stylesheet" href="{{ asset('css/tag.css') }}">
<link rel="stylesheet" href="{{ asset('css/badge.css') }}">
<link rel="stylesheet" href="{{ asset('css/button.css') }}">
<link rel="stylesheet" href="{{ asset('css/button-group.css') }}">
<script>window.TMAGlobalSearchAssetBase = @json(asset('images/'));</script>
<script src="{{ asset('js/tab-group.js') }}" defer></script>
<script src="{{ asset('js/tooltip.js') }}" defer></script>
<script src="{{ asset('js/dash-search-chrome.js') }}" defer></script>
<script src="{{ asset('js/function-bar.js') }}" defer></script>
<script src="{{ asset('js/pagination.js') }}" defer></script>
<script src="{{ asset('js/filter-and-sort.js') }}" defer></script>
<script src="{{ asset('js/table-a.js') }}" defer></script>
<script src="{{ asset('js/table-b.js') }}" defer></script>
<script src="{{ asset('js/table-c.js') }}" defer></script>
<script src="{{ asset('js/table-search.js') }}" defer></script>
<script src="{{ asset('js/table-add-data.js') }}" defer></script>
<script src="{{ asset('js/table-filter-sort.js') }}" defer></script>
<script src="{{ asset('js/global-search.js') }}" defer></script>
<script src="{{ asset('js/toast-icons.js') }}" defer></script>
<script src="{{ asset('js/toast.js') }}" defer></script>
<script src="{{ asset('js/date-picker-icons.js') }}" defer></script>
<script src="{{ asset('js/date-picker.js') }}" defer></script>
<script src="{{ asset('js/popover-icons.js') }}" defer></script>
<script src="{{ asset('js/popover.js') }}" defer></script>
<script src="{{ asset('js/card-icons.js') }}" defer></script>
<script src="{{ asset('js/card.js') }}" defer></script>
<script src="{{ asset('js/input-icons.js') }}" defer></script>
<script src="{{ asset('js/input.js') }}" defer></script>
<script src="{{ asset('js/input-interactive.js') }}" defer></script>
<script src="{{ asset('js/strip-icons.js') }}" defer></script>
<script src="{{ asset('js/strip.js') }}" defer></script>
<script src="{{ asset('js/line-icons.js') }}" defer></script>
<script src="{{ asset('js/line.js') }}" defer></script>
<script src="{{ asset('js/tag-icons.js') }}" defer></script>
<script src="{{ asset('js/tag.js') }}" defer></script>
<script src="{{ asset('js/badge-icons.js') }}" defer></script>
<script src="{{ asset('js/badge.js') }}" defer></script>
<script src="{{ asset('js/button-icons.js') }}" defer></script>
<script src="{{ asset('js/button.js') }}" defer></script>
<script src="{{ asset('js/button-instances-icons.js') }}" defer></script>
<script src="{{ asset('js/button-instances.js') }}" defer></script>
<script src="{{ asset('js/button-group-doc-icons.js') }}" defer></script>
<script src="{{ asset('js/button-group-doc.js') }}" defer></script>
