package com.tmantoinelaw.portal.core.ui.icons

import com.tmantoinelaw.portal.core.ui.R

/**
 * Phosphor icon names (as the API sends them in notifications and file records) to the
 * converted vector drawables. Regenerate the drawables with android/tools/svg2vector.py.
 */
object PhosphorIcons {
    private val byName: Map<String, Int> = mapOf(
        "AddressBook" to R.drawable.ic_address_book,
        "ArrowClockwise" to R.drawable.ic_arrow_clockwise,
        "ArrowCounterClockwise" to R.drawable.ic_arrow_counter_clockwise,
        "ArrowFall" to R.drawable.ic_arrow_fall,
        "ArrowLeft" to R.drawable.ic_arrow_left,
        "ArrowLineDown-16" to R.drawable.ic_arrow_line_down_16,
        "ArrowLineUp" to R.drawable.ic_arrow_line_up,
        "ArrowRight" to R.drawable.ic_arrow_right,
        "ArrowRise" to R.drawable.ic_arrow_rise,
        "ArrowUpRight" to R.drawable.ic_arrow_up_right,
        "ArrowsClockwise" to R.drawable.ic_arrows_clockwise,
        "ArrowsOutCardinal" to R.drawable.ic_arrows_out_cardinal,
        "ArrowsOutSimple" to R.drawable.ic_arrows_out_simple,
        "At" to R.drawable.ic_at,
        "Bell" to R.drawable.ic_bell,
        "Buildings" to R.drawable.ic_buildings,
        "CalendarBlank" to R.drawable.ic_calendar_blank,
        "CalendarCheck" to R.drawable.ic_calendar_check,
        "CalendarPlus" to R.drawable.ic_calendar_plus,
        "CalendarX" to R.drawable.ic_calendar_x,
        "CaretDown" to R.drawable.ic_caret_down,
        "CaretLeft" to R.drawable.ic_caret_left,
        "CaretRight" to R.drawable.ic_caret_right,
        "ChartBar" to R.drawable.ic_chart_bar,
        "ChartPieSlice" to R.drawable.ic_chart_pie_slice,
        "ChatCircle" to R.drawable.ic_chat_circle,
        "ChatCircleText" to R.drawable.ic_chat_circle_text,
        "ChatText" to R.drawable.ic_chat_text,
        "ChatsCircle" to R.drawable.ic_chats_circle,
        "Check" to R.drawable.ic_check,
        "CheckCircle" to R.drawable.ic_check_circle,
        "Clipboard" to R.drawable.ic_clipboard,
        "ClockCountdown" to R.drawable.ic_clock_countdown,
        "ClockCounterClockwise" to R.drawable.ic_clock_counter_clockwise,
        "CloudArrowUp" to R.drawable.ic_cloud_arrow_up,
        "Copy" to R.drawable.ic_copy,
        "DotsThree" to R.drawable.ic_dots_three,
        "DotsThreeVertical" to R.drawable.ic_dots_three_vertical,
        "DownloadSimple" to R.drawable.ic_download_simple,
        "Envelope" to R.drawable.ic_envelope,
        "EnvelopeSimple" to R.drawable.ic_envelope_simple,
        "Eye" to R.drawable.ic_eye,
        "EyeSlash" to R.drawable.ic_eye_slash,
        "File" to R.drawable.ic_file,
        "FileArchive" to R.drawable.ic_file_archive,
        "FileArrowUp" to R.drawable.ic_file_arrow_up,
        "FileAudio" to R.drawable.ic_file_audio,
        "FileCode" to R.drawable.ic_file_code,
        "FilePdf" to R.drawable.ic_file_pdf,
        "FilePlus" to R.drawable.ic_file_plus,
        "FilePpt" to R.drawable.ic_file_ppt,
        "FileText" to R.drawable.ic_file_text,
        "FileVideo" to R.drawable.ic_file_video,
        "FileZip" to R.drawable.ic_file_zip,
        "Flag" to R.drawable.ic_flag,
        "Folder" to R.drawable.ic_folder,
        "FolderNotch" to R.drawable.ic_folder_notch,
        "FolderNotchOpen" to R.drawable.ic_folder_notch_open,
        "FolderNotchPlus" to R.drawable.ic_folder_notch_plus,
        "FolderOpen" to R.drawable.ic_folder_open,
        "FolderPlus" to R.drawable.ic_folder_plus,
        "FolderSimple" to R.drawable.ic_folder_simple,
        "Funnel" to R.drawable.ic_funnel,
        "GearSix" to R.drawable.ic_gear_six,
        "GridFour" to R.drawable.ic_grid_four,
        "House" to R.drawable.ic_house,
        "Info" to R.drawable.ic_info,
        "LinkSimple" to R.drawable.ic_link_simple,
        "ListDashes" to R.drawable.ic_list_dashes,
        "MagnifyingGlassMinus" to R.drawable.ic_magnifying_glass_minus,
        "MagnifyingGlassPlus" to R.drawable.ic_magnifying_glass_plus,
        "Newspaper" to R.drawable.ic_newspaper,
        "Palette" to R.drawable.ic_palette,
        "Paperclip" to R.drawable.ic_paperclip,
        "PenNib" to R.drawable.ic_pen_nib,
        "PencilSimple" to R.drawable.ic_pencil_simple,
        "Phone" to R.drawable.ic_phone,
        "PhoneCall" to R.drawable.ic_phone_call,
        "PhoneX" to R.drawable.ic_phone_x,
        "PlugsConnected" to R.drawable.ic_plugs_connected,
        "Plus" to R.drawable.ic_plus,
        "Printer" to R.drawable.ic_printer,
        "PushPin" to R.drawable.ic_push_pin,
        "PushPinSlash" to R.drawable.ic_push_pin_slash,
        "Rightbar" to R.drawable.ic_rightbar,
        "Rows" to R.drawable.ic_rows,
        "Scissors" to R.drawable.ic_scissors,
        "SealCheck" to R.drawable.ic_seal_check,
        "Search-16" to R.drawable.ic_search_16,
        "ShareNetwork" to R.drawable.ic_share_network,
        "Sidebar" to R.drawable.ic_sidebar,
        "SignOut" to R.drawable.ic_sign_out,
        "Signature" to R.drawable.ic_signature,
        "Smiley" to R.drawable.ic_smiley,
        "SortAscending" to R.drawable.ic_sort_ascending,
        "SortDescending" to R.drawable.ic_sort_descending,
        "Sparkle" to R.drawable.ic_sparkle,
        "SquaresFour" to R.drawable.ic_squares_four,
        "Star" to R.drawable.ic_star,
        "Sun" to R.drawable.ic_sun,
        "Table" to R.drawable.ic_table,
        "Trash" to R.drawable.ic_trash,
        "TrashSimple" to R.drawable.ic_trash_simple,
        "UploadSimple" to R.drawable.ic_upload_simple,
        "UserGear" to R.drawable.ic_user_gear,
        "UserList" to R.drawable.ic_user_list,
        "UserPlus" to R.drawable.ic_user_plus,
        "Users" to R.drawable.ic_users,
        "UsersThree" to R.drawable.ic_users_three,
        "VideoCamera" to R.drawable.ic_video_camera,
        "Warning" to R.drawable.ic_warning,
        "WarningCircle" to R.drawable.ic_warning_circle,
        "X" to R.drawable.ic_x,
        "Xcircle" to R.drawable.ic_xcircle,
    )

    private val byLower: Map<String, Int> = byName.mapKeys { it.key.lowercase() }

    /** The drawable for a Phosphor name (any case: the API sends both `XCircle` and `Xcircle`), else null. */
    fun resolve(name: String?): Int? = name?.let { byName[it] ?: byLower[it.lowercase()] }

    fun resolveOr(name: String?, fallback: Int): Int = resolve(name) ?: fallback
}
