<?php

namespace App\Support\Cip;

/**
 * Countries, and the region each one belongs to.
 *
 * The government form asks for a region, and the firm decided the portal
 * should never ask a person for something it can work out: pick a country of
 * residence and the region follows. Deriving it here rather than in the
 * browser means an application filed through any surface — the wizard, an
 * import, a future API — carries the same answer, and a hand-typed region can
 * never contradict the country beside it.
 *
 * The country list is the one the portal already ships for phone codes
 * (public/js/two-step-countries.js), so a country offered anywhere is a
 * country this map knows.
 */
class Countries
{
    /** country => region. */
    private const REGIONS = [
        'Afghanistan'                              => 'Asia',
        'Albania'                                  => 'Europe',
        'Algeria'                                  => 'Africa',
        'American Samoa'                           => 'Oceania',
        'Andorra'                                  => 'Europe',
        'Angola'                                   => 'Africa',
        'Anguilla'                                 => 'Caribbean',
        'Antigua and Barbuda'                      => 'Caribbean',
        'Argentina'                                => 'South America',
        'Armenia'                                  => 'Asia',
        'Aruba'                                    => 'Caribbean',
        'Australia'                                => 'Oceania',
        'Austria'                                  => 'Europe',
        'Azerbaijan'                               => 'Asia',
        'Bahamas'                                  => 'Caribbean',
        'Bahrain'                                  => 'Middle East',
        'Bangladesh'                               => 'Asia',
        'Barbados'                                 => 'Caribbean',
        'Belarus'                                  => 'Europe',
        'Belgium'                                  => 'Europe',
        'Belize'                                   => 'Central America',
        'Benin'                                    => 'Africa',
        'Bermuda'                                  => 'Caribbean',
        'Bhutan'                                   => 'Asia',
        'Bolivia'                                  => 'South America',
        'Bosnia and Herzegovina'                   => 'Europe',
        'Botswana'                                 => 'Africa',
        'Brazil'                                   => 'South America',
        'British Virgin Islands'                   => 'Caribbean',
        'Brunei'                                   => 'Asia',
        'Bulgaria'                                 => 'Europe',
        'Burkina Faso'                             => 'Africa',
        'Burundi'                                  => 'Africa',
        'Cambodia'                                 => 'Asia',
        'Cameroon'                                 => 'Africa',
        'Canada'                                   => 'North America',
        'Cape Verde'                               => 'Africa',
        'Cayman Islands'                           => 'Caribbean',
        'Central African Republic'                 => 'Africa',
        'Chad'                                     => 'Africa',
        'Chile'                                    => 'South America',
        'China'                                    => 'Asia',
        'Colombia'                                 => 'South America',
        'Comoros'                                  => 'Africa',
        'Congo'                                    => 'Africa',
        'Congo (DRC)'                              => 'Africa',
        'Cook Islands'                             => 'Oceania',
        'Costa Rica'                               => 'Central America',
        'Croatia'                                  => 'Europe',
        'Cuba'                                     => 'Caribbean',
        'Curaçao'                                  => 'Caribbean',
        'Cyprus'                                   => 'Europe',
        'Czech Republic'                           => 'Europe',
        'Denmark'                                  => 'Europe',
        'Djibouti'                                 => 'Africa',
        'Dominica'                                 => 'Caribbean',
        'Dominican Republic'                       => 'Caribbean',
        'Ecuador'                                  => 'South America',
        'Egypt'                                    => 'Africa',
        'El Salvador'                              => 'Central America',
        'Equatorial Guinea'                        => 'Africa',
        'Eritrea'                                  => 'Africa',
        'Estonia'                                  => 'Europe',
        'Eswatini'                                 => 'Africa',
        'Ethiopia'                                 => 'Africa',
        'Falkland Islands'                         => 'South America',
        'Faroe Islands'                            => 'Europe',
        'Fiji'                                     => 'Oceania',
        'Finland'                                  => 'Europe',
        'France'                                   => 'Europe',
        'French Guiana'                            => 'South America',
        'French Polynesia'                         => 'Oceania',
        'Gabon'                                    => 'Africa',
        'Gambia'                                   => 'Africa',
        'Georgia'                                  => 'Asia',
        'Germany'                                  => 'Europe',
        'Ghana'                                    => 'Africa',
        'Gibraltar'                                => 'Europe',
        'Greece'                                   => 'Europe',
        'Greenland'                                => 'Europe',
        'Grenada'                                  => 'Caribbean',
        'Guadeloupe'                               => 'Caribbean',
        'Guam'                                     => 'Oceania',
        'Guatemala'                                => 'Central America',
        'Guinea'                                   => 'Africa',
        'Guinea-Bissau'                            => 'Africa',
        'Guyana'                                   => 'South America',
        'Haiti'                                    => 'Caribbean',
        'Honduras'                                 => 'Central America',
        'Hong Kong'                                => 'Asia',
        'Hungary'                                  => 'Europe',
        'Iceland'                                  => 'Europe',
        'India'                                    => 'Asia',
        'Indonesia'                                => 'Asia',
        'Iran'                                     => 'Middle East',
        'Iraq'                                     => 'Middle East',
        'Ireland'                                  => 'Europe',
        'Israel'                                   => 'Middle East',
        'Italy'                                    => 'Europe',
        'Ivory Coast'                              => 'Africa',
        'Jamaica'                                  => 'Caribbean',
        'Japan'                                    => 'Asia',
        'Jordan'                                   => 'Middle East',
        'Kazakhstan'                               => 'Asia',
        'Kenya'                                    => 'Africa',
        'Kiribati'                                 => 'Oceania',
        'Kosovo'                                   => 'Europe',
        'Kuwait'                                   => 'Middle East',
        'Kyrgyzstan'                               => 'Asia',
        'Laos'                                     => 'Asia',
        'Latvia'                                   => 'Europe',
        'Lebanon'                                  => 'Middle East',
        'Lesotho'                                  => 'Africa',
        'Liberia'                                  => 'Africa',
        'Libya'                                    => 'Africa',
        'Liechtenstein'                            => 'Europe',
        'Lithuania'                                => 'Europe',
        'Luxembourg'                               => 'Europe',
        'Macau'                                    => 'Asia',
        'Madagascar'                               => 'Africa',
        'Malawi'                                   => 'Africa',
        'Malaysia'                                 => 'Asia',
        'Maldives'                                 => 'Asia',
        'Mali'                                     => 'Africa',
        'Malta'                                    => 'Europe',
        'Marshall Islands'                         => 'Oceania',
        'Martinique'                               => 'Caribbean',
        'Mauritania'                               => 'Africa',
        'Mauritius'                                => 'Africa',
        'Mayotte'                                  => 'Africa',
        'Mexico'                                   => 'North America',
        'Micronesia'                               => 'Oceania',
        'Moldova'                                  => 'Europe',
        'Monaco'                                   => 'Europe',
        'Mongolia'                                 => 'Asia',
        'Montenegro'                               => 'Europe',
        'Montserrat'                               => 'Caribbean',
        'Morocco'                                  => 'Africa',
        'Mozambique'                               => 'Africa',
        'Myanmar'                                  => 'Asia',
        'Namibia'                                  => 'Africa',
        'Nauru'                                    => 'Oceania',
        'Nepal'                                    => 'Asia',
        'Netherlands'                              => 'Europe',
        'New Caledonia'                            => 'Oceania',
        'New Zealand'                              => 'Oceania',
        'Nicaragua'                                => 'Central America',
        'Niger'                                    => 'Africa',
        'Nigeria'                                  => 'Africa',
        'Niue'                                     => 'Oceania',
        'North Korea'                              => 'Asia',
        'North Macedonia'                          => 'Europe',
        'Northern Mariana Islands'                 => 'Oceania',
        'Norway'                                   => 'Europe',
        'Oman'                                     => 'Middle East',
        'Pakistan'                                 => 'Asia',
        'Palau'                                    => 'Oceania',
        'Palestine'                                => 'Middle East',
        'Panama'                                   => 'Central America',
        'Papua New Guinea'                         => 'Oceania',
        'Paraguay'                                 => 'South America',
        'Peru'                                     => 'South America',
        'Philippines'                              => 'Asia',
        'Poland'                                   => 'Europe',
        'Portugal'                                 => 'Europe',
        'Puerto Rico'                              => 'Caribbean',
        'Qatar'                                    => 'Middle East',
        'Réunion'                                  => 'Africa',
        'Romania'                                  => 'Europe',
        'Russia'                                   => 'Europe',
        'Rwanda'                                   => 'Africa',
        'Saint Barthélemy'                         => 'Caribbean',
        'Saint Kitts and Nevis'                    => 'Caribbean',
        'Saint Lucia'                              => 'Caribbean',
        'Saint Martin'                             => 'Caribbean',
        'Saint Pierre and Miquelon'                => 'North America',
        'Saint Vincent and the Grenadines'         => 'Caribbean',
        'Samoa'                                    => 'Oceania',
        'San Marino'                               => 'Europe',
        'São Tomé and Príncipe'                    => 'Africa',
        'Saudi Arabia'                             => 'Middle East',
        'Senegal'                                  => 'Africa',
        'Serbia'                                   => 'Europe',
        'Seychelles'                               => 'Africa',
        'Sierra Leone'                             => 'Africa',
        'Singapore'                                => 'Asia',
        'Sint Maarten'                             => 'Caribbean',
        'Slovakia'                                 => 'Europe',
        'Slovenia'                                 => 'Europe',
        'Solomon Islands'                          => 'Oceania',
        'Somalia'                                  => 'Africa',
        'South Africa'                             => 'Africa',
        'South Korea'                              => 'Asia',
        'South Sudan'                              => 'Africa',
        'Spain'                                    => 'Europe',
        'Sri Lanka'                                => 'Asia',
        'Sudan'                                    => 'Africa',
        'Suriname'                                 => 'South America',
        'Sweden'                                   => 'Europe',
        'Switzerland'                              => 'Europe',
        'Syria'                                    => 'Middle East',
        'Taiwan'                                   => 'Asia',
        'Tajikistan'                               => 'Asia',
        'Tanzania'                                 => 'Africa',
        'Thailand'                                 => 'Asia',
        'Timor-Leste'                              => 'Asia',
        'Togo'                                     => 'Africa',
        'Tokelau'                                  => 'Oceania',
        'Tonga'                                    => 'Oceania',
        'Trinidad and Tobago'                      => 'Caribbean',
        'Tunisia'                                  => 'Africa',
        'Turkey'                                   => 'Middle East',
        'Turkmenistan'                             => 'Asia',
        'Turks and Caicos Islands'                 => 'Caribbean',
        'Tuvalu'                                   => 'Oceania',
        'Uganda'                                   => 'Africa',
        'Ukraine'                                  => 'Europe',
        'United Arab Emirates'                     => 'Middle East',
        'United Kingdom'                           => 'Europe',
        'United States'                            => 'North America',
        'Uruguay'                                  => 'South America',
        'Uzbekistan'                               => 'Asia',
        'Vanuatu'                                  => 'Oceania',
        'Vatican City'                             => 'Europe',
        'Venezuela'                                => 'South America',
        'Vietnam'                                  => 'Asia',
        'Virgin Islands (U.S.)'                    => 'Caribbean',
        'Wallis and Futuna'                        => 'Oceania',
        'Yemen'                                    => 'Middle East',
        'Zambia'                                   => 'Africa',
        'Zimbabwe'                                 => 'Africa',
    ];

    /** @return list<string> every country, alphabetically. */
    public static function all(): array
    {
        return array_keys(self::REGIONS);
    }

    public static function isValid(?string $country): bool
    {
        return $country !== null && array_key_exists($country, self::REGIONS);
    }

    /** The region a country sits in, or null when it is not one we know. */
    public static function region(?string $country): ?string
    {
        return self::REGIONS[$country] ?? null;
    }

    /** @return list<array{value: string, label: string, region: string}> */
    public static function options(): array
    {
        $options = [];

        foreach (self::REGIONS as $country => $region) {
            $options[] = ['value' => $country, 'label' => $country, 'region' => $region];
        }

        return $options;
    }
}
